### POST /products/create that returns 200 to Consumer

POST http://localhost:8080/products/create
Content-Type: application/json

{
  "id": "1",
  "name": "Product 1",
  "price": 1,
  "quantity": 2
}


### POST /products/create that returns 404 to Consumer

POST http://localhost:8080/products/create
Content-Type: application/json

{
  "id": "A",
  "name": "Product A",
  "price": 3,
  "quantity": 4
}
